# Generated by Django 4.0.6 on 2022-08-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.TextField()),
                ('Confirm_Password', models.TextField()),
                ('Select_Member', models.TextField()),
                ('Mobile', models.IntegerField()),
            ],
        ),
    ]
