# Generated by Django 4.0.6 on 2022-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.TextField()),
                ('District', models.TextField()),
                ('Local_Address', models.TextField()),
                ('Description', models.TextField()),
                ('Rent', models.TextField()),
                ('Mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.TextField()),
            ],
        ),
    ]
