# Generated by Django 4.0.6 on 2022-08-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loona', '0002_add_property_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_property',
            old_name='State',
            new_name='State1',
        ),
    ]
