# Generated by Django 4.0.6 on 2022-08-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loona', '0003_rename_state_add_property_state1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
