# Generated by Django 4.0.6 on 2022-08-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loona', '0004_delete_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_property',
            name='State1',
        ),
    ]
