# Generated by Django 4.0.6 on 2022-08-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loona', '0006_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adds_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stater', models.TextField()),
                ('District', models.TextField()),
                ('Local_Address', models.TextField()),
                ('Description', models.TextField()),
                ('Rent', models.TextField()),
                ('Mobile', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Add_property',
        ),
    ]
