# Generated by Django 4.0.6 on 2022-08-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loona', '0007_adds_property_delete_add_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='adds_property',
            name='Mobile',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='login',
            name='Email',
            field=models.TextField(),
        ),
    ]
