# Generated by Django 4.0.6 on 2022-08-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loona', '0008_add_state_alter_adds_property_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_state',
            old_name='State',
            new_name='State1',
        ),
    ]
