# Generated by Django 4.0.6 on 2022-08-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loona', '0010_s_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_state',
        ),
        migrations.DeleteModel(
            name='s_state',
        ),
    ]
