# Generated by Django 4.0.6 on 2022-08-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loona', '0011_delete_add_state_delete_s_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stater', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
