# Generated by Django 4.0.6 on 2022-08-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loona', '0012_adds_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='Mobile',
            field=models.TextField(),
        ),
    ]
