# Generated by Django 4.0.6 on 2022-08-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loona', '0013_alter_newuser_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Class', models.TextField()),
                ('Course', models.TextField()),
                ('Punjabi', models.TextField()),
                ('Hindi', models.TextField()),
                ('English', models.TextField()),
                ('Math', models.TextField()),
            ],
        ),
    ]
